### ISSUE TITLE
[BUG]: Video stream not working for two or more peers 

### ISSUE THREAD

**Issue by owais-kali** [Unity-Technologies/com.unity.webrtc#744] opened 2022-06-09 01:30 UTC
### Package version

2.4.0-exp.6

### Environment

```markdown
* OS:Ubuntu 20.04
* Unity version:2020.3.18f1
* Renderstreaming package v3.1.0-exp.3
* WebRTC package v2.4.0-exp.6
```

### Steps To Reproduce

1. Comment out line [124](https://github.com/Unity-Technologies/UnityRenderStreaming/blob/develop/com.unity.renderstreaming/Runtime/Scripts/RenderStreaming.cs#L124) to [135](https://github.com/Unity-Technologies/UnityRenderStreaming/blob/develop/com.unity.renderstreaming/Runtime/Scripts/RenderStreaming.cs#L135) in [Renderstreamer.cs](https://github.com/Unity-Technologies/UnityRenderStreaming/blob/develop/com.unity.renderstreaming/Runtime/Scripts/RenderStreaming.cs)
2. Start RenderStreaming with empty Handlers list
3. Add a GameObject with SingleConnection ,CameraStreamSender & Camera components attached and add this to RenderStreamer handler list at runtime.
4. Execute [CreateConnection(1)](https://github.com/Unity-Technologies/UnityRenderStreaming/blob/develop/com.unity.renderstreaming/Runtime/Scripts/SingleConnection.cs#L25) in SingleConnection.cs component for this gameobject
5. Open Browser and exchange offer and answer using signalling server
6. You should see rendered video on your browser now
7. Repeat the process with another Gameobject with same components but different connection ID.
8.  Open another tab in your browser and exchange offer and answer like before
9. This time you will not receive any video stream in your browser. 

### Current Behavior

Renderstreamer is not working for the second peer.  

### Expected Behavior

See video stream for both users

**Comment by rocco-haro** [comment] 2022-06-09 20:06
@karasusan if you have any webRTC debugging tools you recommend please let us know so that we can further investigate :) thank you in advance!

**Comment by karasusan** [comment] 2022-06-14 02:54
@owais-kali 
You say multiple `SingleConnection` are not worked. Is it right?
The signaling process is succeeded?

**Comment by karasusan** [comment] 2022-06-14 02:56
I think this issue is not caused by WebRTC package. 
It should be fixed in Unity Render Steraming.

**Comment by rocco-haro** [comment] 2022-06-15 15:23
@karasusan Thanks for your response. This issue started occurring after we upgraded the webRTC package while using the latest version of Unity Render Streaming

**Comment by karasusan** [comment] 2022-06-16 01:12
We upgraded the WebRTC package in the develop branch of Uniy Render Streaming. Have you checked this?
https://github.com/Unity-Technologies/UnityRenderStreaming/commits/develop

**Comment by karasusan** [comment] 2022-09-06 02:57
I will close the issue after releasing the latest version of Unity Render Streaming.

**Closed** 2022-10-11 02:45 UTC
Labels: bug, waiting for release
