### ISSUE TITLE
Video stream remains with bad quality after a short network degradation

### ISSUE THREAD

**Issue by eirikwah** [Unity-Technologies/com.unity.webrtc#100] opened 2020-04-22 13:10 UTC
When the bandwidth between server and client is degraded from 20 Mbps to 2 Mbps, the video stream is degraded, and this is expected and works fine. However, when the network is back at 20 Mbps again (for example after 20 seconds), the video stream is not improved even if I wait several minutes. I need to disconnect the client and reconnect to get good video quality again.

Is there a setting/code I should use to fix this, or is it a bug or missing feature?

---
More info on my test setup:

I am testing on Windows x64, running Unity 2019.3.10f1, and Unity Render Stream 2.0.0-preview.4, and thus WebRTC 2.0.0-preview.3. I use HW encoding on the server.

I got the same result on Unity Render Stream version 1.2.3-preview and WebRTC 1.x (or, actually much worse because the HW encoding on bad network gave artefacts that thankfully has been resolved in later versions).

Using SW encoding seems to improve this issue, but it is hard to find a consistent pattern.

I have a very controlled environment for testing and for the bandwidth: The server and client are on the same LAN, and the client runs on Chrome on macOS and I use "Network Link Conditioner" to control the bandwidth on the mac.

Degraded video:
![image](https://user-images.githubusercontent.com/1539783/79985500-fbadce80-84aa-11ea-806a-bf07eb0fdea0.png)

Normal video:
![image](https://user-images.githubusercontent.com/1539783/79985629-2ac44000-84ab-11ea-8c41-b6d32a9118eb.png)

Thank you for this great library! We are looking forward to the next version(s)! :-)

**Comment by karasusan** [comment] 2020-04-23 03:30
I appreciate your report in detail.
OK, I am tackling it.

**Comment by karasusan** [comment] 2020-04-23 06:55
As you say, I found strange results. It might be wrong in the implementation.
I am digging into the native code.

## Sofware encoder
<img width="385" alt="Screen_Shot_2020-04-23_at_3_40_27_PM" src="https://user-images.githubusercontent.com/1132081/80067903-a68cbe00-8579-11ea-8daf-98ffdf4ca6d6.png">

## Hardware encoder
<img width="444" alt="Screen_Shot_2020-04-23_at_2_53_15_PM" src="https://user-images.githubusercontent.com/1132081/80068005-d20fa880-8579-11ea-9676-f6fa4facdf97.png">

**Comment by eirikwah** [comment] 2020-04-23 08:42
Thank you very much for looking into this. Let me know if I can do anything to help (for example testing).

**Comment by eirikwah** [comment] 2020-04-24 13:23
Hi. I have some more test results. Without knowing the details of the code, it looks to me as if the HW encoding use much less bandwidth than is available (except for when the bandwidth is very high). The original resolution of the video stream is 1280x720.

Software rendering, good bandwidth (20 Mbps+):
![image](https://user-images.githubusercontent.com/1539783/80216643-ab677580-863e-11ea-9bfc-9f0e931e1caf.png)


Software rendering, 2Mbps:
![image](https://user-images.githubusercontent.com/1539783/80216695-bcb08200-863e-11ea-9f21-440f49a41bb5.png)


Software rendering, 0,78Mbps:
![image](https://user-images.githubusercontent.com/1539783/80216735-cfc35200-863e-11ea-9986-2125c718a32e.png)


Hardware rendering, good bandwidth (20 Mbps+):
![image](https://user-images.githubusercontent.com/1539783/80216794-e49fe580-863e-11ea-898b-26c29f7058e6.png)


Hardware rendering, 5 Mbps bandwidth. This looks like a bug (the image should not be as blurry as this on 5Mbps ?? ) :
![image](https://user-images.githubusercontent.com/1539783/80216823-f7b2b580-863e-11ea-8aca-c67bedd3533d.png)


Hardware rendering, 2 Mbps:
![image](https://user-images.githubusercontent.com/1539783/80216853-039e7780-863f-11ea-82b3-264ff50d77ee.png)


0,78 Mbps is not much worse than 2 Mbps, and that is a bit surprising:
![image](https://user-images.githubusercontent.com/1539783/80216895-1618b100-863f-11ea-99dd-d3d005b24263.png)

**Comment by karasusan** [comment] 2020-04-27 04:34
Our team investigated this issue but have not solved it.
Sorry for waiting, but we need more time to fix it. We raised the priority of this matter and working on it.

**Comment by eirikwah** [comment] 2020-08-17 06:07
@karasusan  This bug is still appearing. I have also reproduced it on Linux, using HW encoding of the video. Unity Render Streaming version 2.0.2-preview, and WebRTC version 2.0.2-preview.

Could this bug be indirectly fixed by #118, by setting the quality/bitrate explicitly high on the server at regular intervals? Or are you planning any other solution? I see you are working hard on many other features and bugfixes; however, I really hope you will find the time to look more into this. Intermittent network degradation is normal for many users, so this bug will give very many users a very bad video quality.

Please let me know if I can help, for example by testing new versions or testing specific scenarios.

**Comment by karasusan** [comment] 2020-08-18 03:05
I am investigating this issue and I noticed the issue might be caused by libwebrtc made with google. 
I checked the video quality using two of google chrome via WebRTC. 
The issue is reproduced using two of chrome. There is a possibility of a cause is the receiver side.

It is easy to check it if use the sample app "apprtc".

example:
https://appr.tc/?vrc=H264&audio=false&hd=true

Google chrome is using [openh264](https://github.com/cisco/openh264) as h.264 encoder. This package is using NVIDIA Codec SDK instead.
The algorithm of the bitrate control which used by these implementations should be same.
I will investigate a little more.

**Comment by eirikwah** [comment] 2020-08-18 12:18
Thank you for following up, @karasusan .

I tested the sample app "apprtc" between Chrome on macOS and Chrome on Windows 10, and the video quality is restored normally after about 10 seconds when my network goes from bad to good. So I cannot reproduce this bug with Chrome-only test.

Also, to investigate further on my end, I tested with Safari running on an iPad as the "client" to my Unity "server":

- When running against my Unity server (Unity WebRTC 2.0.5-preview) on **Linux using hardware encoding**, I never get good video quality when my network goes from good to bad and back to good (the same result I got when testing on Windows server using HW encoding). 
- But if I use the same Safari on an iPad to run against my Unity server (Unity WebRTC 2.0.5-preview) on **macOS using software encoding**, the video quality **is** gradually improver back to normal quality 10-30 seconds after my network goes from good to bad and back to good (so this works as expected).

**Comment by karasusan** [comment] 2020-08-19 00:52
Thanks for your effort.

> the video quality is restored normally after about 10 seconds when my network goes from bad to good.
Really? Did you set the parameter `vrc=H264` to the URL on the chrome?

As you say, this issue is occurred with only Hardware encoder(H.264) not software encoder(VP8, VP9).

**Comment by eirikwah** [comment] 2020-08-19 05:54
> Really? Did you set the parameter `vrc=H264` to the URL on the chrome?

Yes, I re-checked now and used this URL both on Chome on macOS, and on Windows: https://appr.tc/r/247315345?vrc=H264&audio=false&hd=true. I start with good network, then restrict it to 200 kbps, then wait for 10-15 seconds for the video to switch over to low bandwith (it freezes a short while), then I make the network good again, and after 10-15 seconds the video quality is good again to normal quality. Using Chrome "Version 84.0.4147.125 (Official Build) (64-bit)" on both macOS and Windows.

It would be great if Unity WebRTC would support hardware video encoding with codec VP8 (in addition to H264). We use a "Tesla M60" GPU, which supports HW encoding of VP8. Let me know if there is a way for me to test this (I checked, and it looks like it is unsupported in Unity WebRTC now.)

Another thing I could try is software encoding on Linux, but that is also unsupported in Unity WebRTC now. So currently my backup-plan is to switch from Linux to Windows on our servers, only to be able to do software video encoding. (But I really hope that we don't have to, as this has negative impact on cost and operations for us.)

**Comment by karasusan** [comment] 2020-08-20 09:31
I fixed the issue and now we are testing this PR.

**Comment by WaltzBinaire** [comment] 2020-08-27 17:31
@karasusan We just tested 2.1 and we couldn't find any improvements with regards to the artefacts in hardware encoding. Also changing the bitrate parameters doesn't change the amount of artefacts. Which NVidia drivers are you using?

**Comment by karasusan** [comment] 2020-08-28 02:21
@WaltzBinaire 
This fix is not included in `2.1.0-preview.1`. We will release `2.1.0-preview.3` soon.

About the issue of the bitrate parameters, Could you check it with software encoder?
It might be a bug which occurs with HW encoder.

The package depends on the nvcodec vesion 9.0, 
so NVIDIA driver version R418 or later is no problem.

**Comment by WaltzBinaire** [comment] 2020-08-30 15:55
Hey @karasusan - thank you very much for your amazing efforts ! We woudl have two questions.
1) could you describe the error you fixed in 210preview 3 - it is very interesting to us. 
2) could you let us know when this fix is out. We believe it is super important as unity Webrtc has the same bug since april - and if those artefacts are gone would be a huge game changer in quality of experience!

again thank you very much! we will test the software encoding!

**Comment by karasusan** [comment] 2020-08-31 01:33
I published the WebRTC package 2.1.0-preview.4 and uploaded the template project on GitHub Release.
https://github.com/Unity-Technologies/UnityRenderStreaming/releases/tag/2.1.0-preview

OK, I will add items about fix to the CHANGELOG

**Comment by thomasvanta** [comment] 2020-08-31 16:55
Cross posting, I think this issue is more related:
https://github.com/Unity-Technologies/com.unity.webrtc/issues/164#issuecomment-683701286

Generally it's way more stable.
The bitrate seems to slowly get up over a long period of time.
Couldn't find in the samples the right place to change the bitrate.

**Comment by WaltzBinaire** [comment] 2020-08-31 17:06
Hey it really seems as if #164 is related - latest preview is a massive jump in quality ! Thank you guys. However it seems now that in the beginning the bandwidth ramps up unnecessary slow for up to 20 seconds as if it started at zero. The frequent bumps however seem to be completly gone. We also couldnt get the bitrate settings to work

**Comment by mickeyvanolst** [comment] 2020-08-31 17:08
Can confirm, quality seems to be bad for about 15-20 seconds and then goes back to normal.

**Comment by karasusan** [comment] 2020-09-01 01:28
@WaltzBinaire 

> However it seems now that in the beginning the bandwidth ramps up unnecessary slow for up to 20 seconds as if it started at zero. 

> We also couldnt get the bitrate settings to work

I am investigating them.

**Comment by WaltzBinaire** [comment] 2020-09-02 09:32
hey @karasusan -where you able to find out why the connection ramps up so slowly? thank you!

**Comment by eirikwah** [comment] 2020-09-04 06:44
The originally reported bug is now fixed: I can confirm that the image quality is restored 10-20 seconds after the network quality has gone from bad to good. This is in version 2.1.0-preview.4. Thanks, @karasusan .

**Comment by karasusan** [comment] 2020-09-08 10:27
https://github.com/Unity-Technologies/com.unity.webrtc/issues/100#issuecomment-684136999

> However it seems now that in the beginning the bandwidth ramps up unnecessary slow for up to 20 seconds as if it started at zero.

@WaltzBinaire created an issue about that.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/182

> We also couldnt get the bitrate settings to work
I created an issue.
https://github.com/Unity-Technologies/com.unity.webrtc/issues/183

I am glad if you post information about these issues.
I guess the original issue is already done, may I close this one? > @eirikwah

**Comment by eirikwah** [comment] 2020-09-08 12:13
Yes, I agree that this issue should be closed, because the originally reported bug has been fixed. 🏅

**Closed** 2020-09-09 01:07 UTC
Labels: bug
