### ISSUE TITLE
[BUG] Many dropped frames on Linux from version 2.0.5

### ISSUE THREAD

**Issue by eirikwah** [Unity-Technologies/com.unity.webrtc#180] opened 2020-09-07 10:33 UTC
**Describe the bug**

On Linux, from (and including) Unity WebRTC version 2.0.5, the image is stuttering and have many dropped frames.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use Unity WebRTC 2.0.5.preview or newer. Use Linux as server (this can not be reproduced on macOS or Windows)
1. Create a spinning cube (or other smooth animation)
2. Connect a client (I used Chrome on macOS, but this is probably not relevant)
3. Observe that the animation has freezes and dropped frames

**Expected behavior**

No dropped frames/freezes, as seen in version 2.0.4.preview and older.

**Screenshots**

The exact same app on the exact same network and same hardware. The only difference is the version of Unity WebRTC.

Unity WebRTC 2.0.4.preview webrtc stats from browser (all is normal):
![stats-webrtc-2 0 4 preview-smooth](https://user-images.githubusercontent.com/1539783/92377917-34221200-f105-11ea-9cb1-b189097b8c90.png)

Unity WebRTC 2.0.5.preview webrtc stats from browser (with the bug):
![stats-webrtc-2 0 5 preview-stuttering](https://user-images.githubusercontent.com/1539783/92377948-3d12e380-f105-11ea-9843-798de006bde4.png)

Side-by-side comparison of the smooth and jagged animation (download, unzip and play video, if the animated GIF is too coarse):
[spinning_cube_2.0.0vs2.1.0.mov.zip](https://github.com/Unity-Technologies/com.unity.webrtc/files/5182575/spinning_cube_2.0.0vs2.1.0.mov.zip)
![spinning_cube_2 0 0vs2 1 0](https://user-images.githubusercontent.com/1539783/92378409-0ab5b600-f106-11ea-8568-f945ca623379.gif)

**Environment (please complete the following information):**
 - OS: Ubuntu 18
 - Browser: Chrome on macOS
 - Unity Version: 2019.4.9f1
 - Package version: 2.0.5-preview

**Additional context**
I previously believed that this was related to #164, but I think this issue is different.

**Comment by karasusan** [comment] 2020-09-07 11:45
This is a diff of 2.0.4 and 2.0.5. The changes is for upgrading libwebrtc.
https://github.com/Unity-Technologies/com.unity.webrtc/compare/2.0.4-preview...2.0.5-preview

Is this a problem specific to on Linux?  It should be also reproduced on other platform.

**Comment by eirikwah** [comment] 2020-09-07 12:04
I am only able to reproduce this bug on Linux. Maybe the bug was introduced by the new webrtc dependency, or maybe the small differences in buffer initialization?

 However, I did find another important difference between my test on Windows and Linux: I have been using the default `Application.targetFrameRate`, and this is 60 on Windows, and about 180 on my Linux VM.

I have re-tested now on Linux, using `Application.targetFrameRate = 30;`, and this removed the bug for us. The rotating cube is now smooth (in 30 FPS), and the stats look normal:

![stats-webrtc-2 1 0 preview 4-30fps-smooth](https://user-images.githubusercontent.com/1539783/92385788-c846a600-f112-11ea-94fb-0309ee38adcc.png)

So for our case, this bug is not important any more, when we have this workaround. Thanks for your help.

**Comment by karasusan** [comment] 2020-09-08 06:02
Wow, I have never known the `Application.targetFrameRate` affects the stability of video streaming quality.
I am relieved that you found a workaround the issue.
OK, the behavior should be fixed, we will investigate it for the next version 2.2.

**Comment by eirikwah** [comment] 2020-09-25 10:41
I have an update on this issue: I have tested much more, and learned that:

- My old code has been setting start bitrate and max bitrate by manipulating the SDP text. This has contributed to "strange" behaviour: This is probably the reason for the change from version 2.0.5.
- My old code used way too high values for start bitrate and max bitrate: Start at 20 Mbps, and have max 40 Mbps. So some stuttering/dropped frames are because my network link was saturated.

After removing the old code that manipulated the SDP text, upgrading to the WebRTC package to version 2.1.1-preview and instead setting maxBitrate to 10 Mbps with `RTCRtpSender.SetParameters(...)`, I can have much higher framerate again, without getting dropped or freezed frames.

**Comment by karasusan** [comment] 2020-09-26 02:16
@eirikwah 
You are reporting the important things every time so I am very appreciative.

In my opinion, the load of the render thread tends to become high when set a high frame rate. 
Because of this causes, it should affects the stability of  video streaming.

Already I have a plan that to decrease the load of the render thread.

**Comment by karasusan** [comment] 2020-09-27 00:41
We will start to work to reduce the load of the render thread from next milestone.

**Comment by karasusan** [comment] 2020-12-08 01:38
Related issue
https://github.com/Unity-Technologies/com.unity.webrtc/issues/205

**Comment by karasusan** [comment] 2022-01-18 02:16
There is a same ticket [here](https://github.com/Unity-Technologies/com.unity.webrtc/issues/205).
We will close this issue if nothing reply.

**Closed** 2022-02-02 03:04 UTC
Labels: bug, duplicate, stabled
