### ISSUE TITLE
[BUG] Bandwidth goes up slowly on every new sesssion

### ISSUE THREAD

**Issue by WaltzBinaire** [Unity-Technologies/com.unity.webrtc#182] opened 2020-09-08 08:36 UTC
**Describe the bug**
When starting the demo you will see the image quality ramping up slowly everytime you create a new connection. 

It seems almost animated as if a control value was not initialized and interpolates up over time.

**To Reproduce**
Only on 2.1.0
Start demo - local or on server.
Bad quality on startup slowly progressing to full quality over 15-30 seconds

**Expected behavior**
A quick recovery of the image quality matching the actual bandwidth

**Screenshots**

![Ramp](https://user-images.githubusercontent.com/1371546/92453104-27fa8b00-f1bf-11ea-897d-28ed75729f04.jpg)

**Environment (please complete the following information):**
 - Windows 64
 - Chrome
 - Unity Version  2019.4.9f1
 -  2.1.0-preview.4

**Additional context**
Bug was introduced in 2.1.0 - we couldnt find this particular behavior before.

**Comment by WaltzBinaire** [comment] 2020-09-09 07:43
let us know if there is any way we can help testing

**Comment by karasusan** [comment] 2020-09-14 07:27
@WaltzBinaire 

To fix this issue, I erased the operation of using customized SDP.
Please check it.

**Comment by WaltzBinaire** [comment] 2020-09-15 08:19
hey @karasusan ,

thank you! Unfortunatly we cant verify it gettign better. Let us know if we can help testing.

![Unbenannt](https://user-images.githubusercontent.com/1371546/93184729-df9e1880-f73c-11ea-83d2-c700033d8d7f.JPG)

**Comment by karasusan** [comment] 2020-09-15 08:38
This issue is caused by the customized SDP.
Could you check your Unity project and web application whether they customize SDPs.
https://github.com/Unity-Technologies/UnityRenderStreaming/pull/331

**Comment by WaltzBinaire** [comment] 2020-09-15 10:07
Hey yes please ignore my previous post. I just checked it and it works! The bandwidth rises quickly. 
BUT it brings back the previous issue #164 . It seems when you solved issue #164 you introduced the slow bandwith in the beginning that wasnt there before - now that the slow bandwidth in the beginning is solved - we can see the #164 again.

**Comment by karasusan** [comment] 2020-09-15 23:04
I am glad to help you.
Can I reopen the issue #164? I guess it might be better to create a new one.

I expect the input system is the cause of it, but there is no proof of that yet.
Do you have any other clues?

**Comment by WaltzBinaire** [comment] 2020-09-16 00:02
Hey @karasusan - yes i think we should reopen the issue. The challenge here is that multiple issues seem to be connected to the same procesures - and that makes it important to tackle the moment they start to appear. From our side:
1) there were two issues : dropping bitrate/artefacts and input lack
2) around 2.1.0 : both problems solved - but slow ramp on bandwidth in the beginning
3) you reverted changes : bitrate/artefacts look ok - slow ramp bandwidth solved - but input lack comes back

I believe all those issues spin around the lines that control sdp - and i think this is the most important issuebof the repo - since control and quality determine the overall quality.

However im als not able to tackle the issue - really sorry!

**Comment by WaltzBinaire** [comment] 2020-09-16 00:04
@karasusan Are you able to recreate the input lack? #164

**Comment by karasusan** [comment] 2020-09-16 01:39
@WaltzBinaire
OK, I reopened the issue #164, we will be able to discuss in it instead of here.
I close this issue, thanks.

**Closed by karasusan** 2020-09-16 01:39 UTC
Labels: bug
