### ISSUE TITLE
[BUG] I cannot get the Unity host to send more than about 2.5mbps to Chrome with ANY encoder

### ISSUE THREAD

**Issue by yvanzine** [Unity-Technologies/com.unity.webrtc#552] opened 2021-11-05 16:04 UTC
Hi, 

I would like to reopen bug #518, but add more detail to this issue. If anyone has additional information, please contribute, especially @doctorpangloss @karasusan.

I cannot see bitrate rise at all above 2.5 mbps in webrtc-internals. 

Things I have tried:
1) Switching hardware and software codec does not help
2) Upgrading encoder to 6.2. Even though it does bring about more stability, i.e. the nvidia reincode api does not throw exceptions any more, the bitrate does not increase, and so it follows that quality will not improve.
3) Setting minBitrate, maxBitrate, averageBitrate does not help, because there is the overriding max bitrate of 2.5 mbps (possibly from client?)
4) Setting maxFramerate to 10-30 fps, which does help to control available bitrate (under 2.5Mbps)
5) overriding incoming Context::SetRates to be more than 2.5mbps does not help, and my theory is that the client will not consume more than 2.5mbps and therefore the forced change of bitrate does not "stick".

I would love to see proof that it is possible to unbind max bitrate to above 2.5mbps. In version 2.1.3, it used to work, so we must have a regression: https://github.com/Unity-Technologies/com.unity.webrtc/pull/195

My environment:
Linux, Ubuntu 20.04
Chromium 95.
Unity Version [e.g. 2020.3.12f1]
Packages:
[com.unity.webrtc 2.3.3-preview]
[UnityRenderStreaming 3.0.1-preview]

**Comment by karasusan** [comment] 2021-11-08 23:30
Thanks for checking.
In PR #195, I think this line would be possible to change the behavior. But this line might not affects software encoder.
https://github.com/Unity-Technologies/com.unity.webrtc/pull/195/files#diff-0f297a3ca5590dd245628f74a53684359fa2c445965cf2257436d41d43d7867aL137-R137

Could you try to revert this line for that?

**Comment by yvanzine** [comment] 2021-11-09 17:17
@karasusan 

The line you are pointing to, does not make a significant difference, but it adjusts more correctly. Instead of a fixed 2.5mbps, the adjustment will occur and the bitrate will vary slightly, in my experiment, it goes between 2.3 and 2.5mbps. 

I think this revert will be required as part of overall regression revert.

As I promised, I did some regression testing yesterday. I officially confirm the regression of fixed 2.5mbps occured. I recreated my identical scene in these releases, and eliminated any of my own changes.

**2.1.1-preview** 

the image quality is high, no fuzzy, in and out of focus pixelation. When animation or camera manipulation happens, the quality is constant and the only change is in bitrate.

The bitrate is unbounded, I can see it spike up properly:

![2 1 1-preview-2](https://user-images.githubusercontent.com/19309404/140971432-57682b72-3a1b-4c36-b59a-a7c93c6a313b.png)

**3.0.1-preview**

The artifacts are there, smearing, degraded quality overall, the bitrate never exceeds 2.5Mbps
![3 0 1-preview](https://user-images.githubusercontent.com/19309404/140972106-f0acb457-a1b6-4c09-9333-766e3094a31d.png)

So my plan is to diff between these two releases and then comb through your commits in the context of all the changes that took place between 2.1.1-preview and 3.0.1-preview in both render streaming and webrtc packages. I see no other plan to fix bitrate.

**Comment by yvanzine** [comment] 2021-11-09 23:32
**2.2.2-preview**  render streaming (webrtc 2.1.1-preview)

is already exhibiting the 2.5 Mbps bitrate max regression:

![renderstreaming_2 2 2](https://user-images.githubusercontent.com/19309404/141022288-2a90badc-7e4e-4bec-bc6e-f8abe1c71aac.png)

**Comment by yvanzine** [comment] 2021-11-09 23:38
@karasusan 

I will continue diffing between webrtc 2.1.1-preview and webrtc 2.2.1-preview as I isolated the regression to that range.

https://github.com/Unity-Technologies/com.unity.webrtc/compare/2.1.1-preview...2.2.1-preview

I do not see anything suspicious yet and I am wondering if libwebrtc upgrade may play a role.

**Comment by yvanzine** [comment] 2021-11-11 00:49
@karasusan 

This is interesting and unexpected. I was tracking the bitrate regression further and I decided to "fix" the webrtc package version at 2.1.3-preview and change render streaming package version. This version includes both the encoder upgrade and the libwrtc upgrade that I was suspecting of creating the bitrate issue.

I found that render streaming package at 2.1.1-preview has unbounded bitrate. Render streaming package at 2.2.0 has 2.5 mbps maximum. All the time I keep webrtc package at 2.1.3-preview.

This change is much smaller which is fantastic but I cannot explain where this regression ends up happening yet. You add coroutines for signaling into RenderStreaming.cs. Maybe some sdp negotiation keeps resetting the bitrate, but unlikely.

[2.1.1-preview...2.2.0-preview](https://github.com/Unity-Technologies/UnityRenderStreaming/compare/2.1.1-preview...2.2.0-preview)

**Comment by karasusan** [comment] 2021-11-11 02:33
@yvanzine
Thank you for your sharing. We will prioritize this issue.

**Comment by yvanzine** [comment] 2021-11-12 16:29
@karasusan 

Removing HTTPGetAnswers() from HttpSignaling.cs brings back unbounded bitrate for me testing in render streaming 2.2.0-preview. Doing the same in later versions of render streaming does not. I think what that tells me is that somewhere in sdp offer-answer we are severely restricting bitrate and creating a quality issue.

``` 
HTTPGetOffers();
//HTTPGetAnswers();
HTTPGetCandidates();
```

**Comment by karasusan** [comment] 2021-11-16 03:44
memo: WRS-155

**Comment by yvanzine** [comment] 2021-11-16 19:37
@karasusan 

I do not know why it took me so long to find where exactly we are limiting the bitrate, but here it is. If we do not munge the received offer at the Unity Client to set up maximum bitrate in the sdp message, then the bitrate never grows. This code was removed from render streaming in 2.1.1-preview.

```
//make video bit rate starts at 16000kbits, and 160000kbits at max.
string pattern = @"(a=fmtp:\d+ .*level-asymmetry-allowed=.*)\r\n";
e.sdp = Regex.Replace(e.sdp, pattern, "$1;x-google-start-bitrate=16000;x-google-max-bitrate=160000\r\n");
```

I will be running with this sdp munging block of code and testing any side effects as this works in any subsequent version of render streaming package.

**Comment by karasusan** [comment] 2021-11-17 01:50
@yvanzine
You mean we need to munge SDP to determine the bitrate, is it right?

**Comment by yvanzine** [comment] 2021-11-17 04:15
Yes

**Comment by doctorpangloss** [comment] 2021-11-21 06:47
I don't use this munging, and I've successfully gotten high bitrates for a while now.

<img width="983" alt="Screen Shot 2021-11-20 at 10 44 47 PM" src="https://user-images.githubusercontent.com/2229300/142752599-83870420-5f34-4c31-a23c-e258e7f40419.png">

I will look closely at what I am doing differently.

**Comment by doctorpangloss** [comment] 2021-11-21 06:49
> @karasusan
> 
> Removing HTTPGetAnswers() from HttpSignaling.cs brings back unbounded bitrate for me testing in render streaming 2.2.0-preview. Doing the same in later versions of render streaming does not. I think what that tells me is that somewhere in sdp offer-answer we are severely restricting bitrate and creating a quality issue.
> 
> ```
> HTTPGetOffers();
> //HTTPGetAnswers();
> HTTPGetCandidates();
> ```

I think this is a red herring.

**Comment by doctorpangloss** [comment] 2021-11-21 06:51
@yvanzine check that you are not accidentally setting the RTPSender's parameters in kilobits. It takes bits, not kilobits. So to specify a 25mbit bitrate, set the bitrate to `25000000`, not `25000`.

**Comment by yvanzine** [comment] 2021-11-22 03:56
@doctorpangloss Yes, I made sure to set RTPSender encoding settings in bps but these settings only apply if you are under 2500 bps. 

Maybe there are other things you can remember that you did since you are not using sdp munging. What did it for me was setting the x-google-max-bitrate value explicitly. According to the docs, the max bitrate is a default 2500 kbps if you do not set it. 

There is also a new problem I want to bring up. At some point ( I suspect when packet loss reaches a certain threshold, e.g. 10%) the bitrate drops to almost 0 and never recovers.

This only happens in a server cloud deployment, I have never seen it in development localhost scenario.

**Comment by doctorpangloss** [comment] 2021-11-22 05:28
> in a server cloud deployment
I host only inside Windows DirectX11 and DirectX12. Would that matter? I never test Vulkan.

**Comment by yvanzine** [comment] 2021-11-22 15:33
@doctorpangloss 

In the course of my testing of this particular issue (max bitrate and additionally bitrate plummeting to 0), I am very much convinced that the server configuration plays no role and SDP very much does, maybe because I see degraded session and no recovery in the same connection. I have patched the RTPSender encoding settings on the unity side and I am able to set maximum framerate (contrary to the forum here). I am running on Linux kubernetes VM, rendering with Vulkan and I have upgraded the nvidia encoder. I have seen the same issue of 2.5 mbps max bitrate on a software encoder. Your screenshot of unbounded bitrate is contradicting my experience and I would like to know what it took for you to achieve that.

**Comment by yvanzine** [comment] 2021-11-22 15:54
@karasusan @doctorpangloss 

I have been able to reproduce the bitrate drop to 0 100% of the time by simulating network packet loss of 10%. The result is what I see in the server environment. But as soon as I turn off packet loss, the connection recovers (which is different but maybe constant packet loss for some clients is a reality).

We should look why the bitrate collapses and not degrades in the presence of packet loss.

I understand this may be webrtc code in chromium that should handle that. Maybe looking to upgrade to a newer libwebrtc can address that?

**Comment by karasusan** [comment] 2021-11-30 06:08
@doctorpangloss, @yvanzine
Is this issue relating platforms(Linux, Windows)?

**Comment by yvanzine** [comment] 2021-12-10 16:59
@karasusan 

I confirm this issue (having to munge SDP to avoid the bitrate max at 2.5Mbps ) affects both Windows and Linux and you can observe with and without behavior on either OS.

**Comment by karasusan** [comment] 2021-12-14 03:44
@yvanzine
Sure, Thanks. 
We will investigate the way to change the limitation 2.5Mbps, and provide API for that.

**Comment by kannan-xiao4** [comment] 2022-02-02 02:22
@yvanzine 
I was able to reproduce it.
We will continue to investigate, but it looks like take some time to fix.

**Comment by matt-knowles-level-ex** [comment] 2022-04-21 06:35
Not sure if anyone else is still hitting the capped at 2.5 Mbps issue. Adding a "b=AS:maxkbits" after your "a=mid:0" frees it up. a=mid:0 is the video block for our SDP.

 // add b:AS:maxbitrate after a=mid:0 
 string midPattern = @"(a=mid:0\r\n)";
 // () around pattern gives access to insert found match with $1
 newSDP = Regex.Replace(originalSDP, midPattern, "$1" + $"b=AS:{maxKbits}\r\n");

Using the latest soon to be released 2.4.0-exp.7 this fixes the capped bitrate. We do see dips in the bitrate every 10 to 15 seconds with this new code. Each dip is about 50% of the bitrate then recovers in 2 to 3 seconds.

Matt

**Comment by doctorpangloss** [comment] 2022-04-21 21:11
The bitrate is set here:
https://github.com/Unity-Technologies/com.unity.webrtc/blob/306cb714903b5e50711008a75885c2d59806ba93/Plugin~/WebRTCPlugin/Codec/NvCodec/NvEncoderImpl.cpp#L414
 - @karasusan the bitrate adjustment here is causing the dip in bitrate, it's redundant.
 - When directly connected to a host (ICE candidate was type = `host`) I don't observe any issues.
 - When connected to Twilio's relay, the max network bandwidth available is reported as 350kbps.

**Comment by karasusan** [comment] 2022-04-22 01:16
@doctorpangloss
Sure, I will check the line.

**Comment by doctorpangloss** [comment] 2022-04-22 03:30
@karasusan try testing with `relayOnly` with the Twilio relay servers. This reproduces a lot of issues and is a pretty realistic environment. That reproduces bandwidth issues for me.

**Comment by karasusan** [comment] 2022-04-22 09:21
@doctorpangloss
I am not familiar the Twilio relay servers. Is this?
https://www.twilio.com/stun-turn

**Comment by doctorpangloss** [comment] 2022-04-22 17:34
> @doctorpangloss I am not familiar the Twilio relay servers. Is this? https://www.twilio.com/stun-turn

That's correct.

**Comment by yvanzine** [comment] 2022-04-22 17:38
@doctorpangloss Is there a benefit to using twilio for cloud-hosted unity webrtc video-only server? Can you please share some information?

**Comment by doctorpangloss** [comment] 2022-04-25 17:46
Update:
@matt-knowles-level-ex resolution works to remove bitrate caps. Munge **both** the answer and offer SDPs that ultimately get set by their respective peers. I use logic similar to https://github.com/wiegell/spreed/commit/5c94fe6feb554810f0e509fdaf3eff34cc7bd0b1

@karasusan Removing bitrate allocator and relying solely on the passed rates works correctly.

**Comment by karasusan** [comment] 2022-04-26 01:29
@doctorpangloss
Sure, I will check it. Thanks

**Comment by doctorpangloss** [comment] 2022-04-26 08:25
Update:
It looks like the bitrate allocator is necessary, but it isn't being used 100% correctly right now. My workaround is to ask NVIDIA to encode at 80% of the `parameters.bitrate`.

**Comment by karasusan** [comment] 2022-05-10 02:44
@doctorpangloss
Interesting. Let me try.

**Comment by kannan-xiao4** [comment] 2022-05-10 04:50
@doctorpangloss 
I tried to set max bitrate 25mbps on current develop branch.
Bitrate not limited by 2.5mbps, it maybe almost same value as  `bytes_per_frame * fps`.
But if set high bitrate (ex. 25mbps) with H264 codec,  crash happend.
Does your workaround is for this crash?

I'll fix this crash until next release.

@yvanzine 
If you like, try it in your environment.
This change will be included in the next package version release.

**Comment by yvanzine** [comment] 2022-05-10 14:11
@kannan-xiao4 

About the crash. Did you upgrade the nvidia encoder to 6.2? I have seen all crashes related to resolution or bitrate capacity go away. 

`nvEncConfig.encodeCodecConfig.h264Config.level = NV_ENC_LEVEL_H264_62;`

**Comment by karasusan** [comment] 2022-05-13 07:28
@yvanzine
Your issue would be fixed this PR.
https://github.com/Unity-Technologies/com.unity.webrtc/pull/721

**Closed** 2022-05-17 11:49 UTC
Labels: bug, waiting for release, issued
