### ISSUE TITLE
[BUG]: Potential uneven framerate issue with vkQueueWaitIdle()

### ISSUE THREAD

**Issue by yvanzine** [Unity-Technologies/com.unity.webrtc#714] opened 2022-04-27 22:33 UTC
### Package version

2.4.0-exp.7

### Environment

```markdown
Package version
2.4.0-exp.7

Environment
Linux, Ubuntu 20.04
Chromium 100.0.4896.127.
Unity Version 2020.3.24f1
Packages:
[com.unity.webrtc 2.4.0-exp.7]
[UnityRenderStreaming experimental/webrtc-2.4.0-exp.7 branch]
```

### Steps To Reproduce

Run on Vulkan graphics device.

### Current Behavior

**vkQueueWaitIdle()** executed multiple times per frame leads to a render pipeline bubble( no render commands are executed while waiting ),  may be contributing to framerate issues and generally process render commands suboptimally.

VkResult VulkanUtility::EndAndSubmitOneTimeCommandBuffer(const VkDevice device, const VkCommandPool commandPool, const VkQueue queue, VkCommandBuffer commandBuffer)
{
    vkEndCommandBuffer(commandBuffer);

    VkSubmitInfo submitInfo = {};
    submitInfo.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
    submitInfo.commandBufferCount = 1;
    submitInfo.pCommandBuffers = &commandBuffer;

    VULKAN_CHECK(vkQueueSubmit(queue, 1, &submitInfo, VK_NULL_HANDLE));
    VULKAN_CHECK(vkQueueWaitIdle(queue));

    vkFreeCommandBuffers(device, commandPool, 1, &commandBuffer);

    return VK_SUCCESS;
}

### Expected Behavior

Calls to **vkQueueWaitIdle()** should not be made.

**Comment by karasusan** [comment] 2022-04-28 01:17
@yvanzine 
I am completely agree. We have already found that the Vulkan implementation is low performance than other graphics APIs. As you said, probably it is the one of the cause of the performance issue.

**Comment by kannan-xiao4** [comment] 2022-05-10 02:34
memo: WRS-299

**Comment by EricUUU** [comment] 2022-05-17 09:54
Hello, how does H264 decoder receive I-frame message and set I-frame.  @karasusan  Help me

**Comment by karasusan** [comment] 2022-05-17 11:47
@EricUUU
Your comment is not related this issue. Please make a new issue.

**Comment by karasusan** [comment] 2022-06-24 01:27
@yvanzine
This PR is already merged.
https://github.com/Unity-Technologies/com.unity.webrtc/pull/750

**Closed** 2022-07-13 02:43 UTC
Labels: bug, waiting for release, issued
