### ISSUE TITLE
[BUG]: Track is disposed after calling ReplaceTrack

### ISSUE THREAD

**Issue by kayy** [Unity-Technologies/com.unity.webrtc#912] opened 2023-05-10 18:26 UTC
### Package version

3.0.0-pre.5

### Environment

```markdown
* OS: Windows 11
* Unity version: 2020.3.45
```

### Steps To Reproduce

- Set up a working WebRTC connection 
- After some time
  - Create a new VideoStreamTrack on the fly **without holding a reference permanently**
  - Call RTCRtpSender.ReplaceTrack(track)
 

### Current Behavior

After a few seconds the stream gets frozen

### Expected Behavior

The stream remains active

### Anything else?

The initial track created with MediaStream.AddTrack is cached internally in a HashSet cacheTracks. Thus this will run without any issues.  
Replacing a track breaks this behaviour. Thus the caller need to hold a reference to avoid disposing the track. 

Underlying use case: Dynamic resizing of tracks in response to size changes in the HTML part. Calling ReplaceTrack method avoids renegotiation and the tracks are created on the fly without any need to to take care them.

**Comment by kayy** [comment] 2023-05-11 06:29
The following patch modifies the ReplaceTrackSample.cs in that stream2 is created on the fly. After 1-2 seconds it freezes.  

Maybe this was intentionally and by design, but in this case this should be documented and MediaStream.AddTrack should behave the same way.
[ReplaceTrackSample_stream2-local.patch](https://github.com/Unity-Technologies/com.unity.webrtc/files/11449064/ReplaceTrackSample_stream2-local.patch)

**Comment by karasusan** [comment] 2023-05-16 05:44
memo: WRS-478

**Comment by karasusan** [comment] 2023-09-28 06:31
I am sorry to reply lately.
I checked the sample code. As you said, this behaviour is by design.

I would like to add comments to **MediaStream** class and **Camera.CaptureStreamTrack** method.


- MediaStream class has references of VideoStreamTrack to avoid Garbage Collection.
- You need to hold references of VideoStreamTrack which is created by Camera.CaptureStreamTrack, this instance is collected by GC if you don't hold references.

**Comment by karasusan** [comment] 2023-10-13 07:38
@kayy
Can I close this issue?

**Comment by kayy** [comment] 2023-10-13 10:38
> @kayy Can I close this issue?

Yes. Adding some comments is fine

**Comment by karasusan** [comment] 2023-10-16 02:32
https://github.com/Unity-Technologies/com.unity.webrtc/pull/995

**Closed** 2023-11-01 00:58 UTC
Labels: bug, waiting for release, issued
