### ISSUE TITLE
[BUG] Editor Crashing (on some machines) when calling RTCPeerConnection constructor

### ISSUE THREAD

**Issue by Angelo-Gebauer** [Unity-Technologies/com.unity.webrtc#320] opened 2021-02-18 11:08 UTC
**Describe the bug**
The editor crashes when calling `new RTCPeerConnection(ref configuration)`. 
We tested in three different environments, the crash happens in two of them.

Here's the code:
```csharp
...
var configuration = GetSelectedSdpSemantics();
peerConnection = new RTCPeerConnection(ref configuration);
}

private RTCConfiguration GetSelectedSdpSemantics()
{
  RTCConfiguration config = default;
  config.iceServers = new[] { new RTCIceServer { urls = new[] { "stun:stun.l.google.com:19302" } } };
  return config;
}
```

The machines/setups where it crashed:

- Machine 1
  - Windows 10
  - Ryzen 7 3700x
  - RTX 2070 Super
  - Unity **2020.2.3f4 AND** Unity **2020.2.4f1**
  - com.Unity.WebRTC **2.3.1 AND** com.Unity.WebRTC **2.3.2**

- Machine 2
  - macOS 11.2.1
  - Core i7 9750H
  - Radeon Pro 5300M
  - Unity **2020.2.4f1**
  - com.Unity.WebRTC **2.3.1 AND** com.Unity.WebRTC **2.3.2**

The machine/setup where it worked:
- Machine 1
  - Windows 10
  - Some i7 8th or 9th gen
  - RX 5700XT
  - Unity **2020.2.4f1**
  - com.Unity.WebRTC **2.3.2**

<p>
<details>
<summary>Editor Log from crash:</summary>
<pre><code>
Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) Unity.WebRTC.NativeMethods.ContextCreatePeerConnectionWithConfig (intptr,string) [0x00014] in <c3e4568803844d0e9c4f6bbefd65cb54>:0
  at Unity.WebRTC.Context.CreatePeerConnection (string) [0x00000] in D:\Unity Projects\ArWebRTCPrototyp\ArWebRTCPrototyp\Library\PackageCache\com.unity.webrtc@2.3.1-preview\Runtime\Scripts\Context.cs:82
  at Unity.WebRTC.RTCPeerConnection..ctor (Unity.WebRTC.RTCConfiguration&) [0x00017] in D:\Unity Projects\ArWebRTCPrototyp\ArWebRTCPrototyp\Library\PackageCache\com.unity.webrtc@2.3.1-preview\Runtime\Scripts\RTCPeerConnection.cs:437
  at WebRtcReceiver.SetUpPeerConnection () [0x00011] in D:\Unity Projects\ArWebRTCPrototyp\ArWebRTCPrototyp\Assets\Scripts\WebRtcReceiver.cs:101
  at WebRtcReceiver.Start () [0x0006f] in D:\Unity Projects\ArWebRTCPrototyp\ArWebRTCPrototyp\Assets\Scripts\WebRtcReceiver.cs:40
  at (wrapper runtime-invoke) object.runtime_invoke_void__this__ (object,intptr,intptr,intptr) [0x00020] in <9577ac7a62ef43179789031239ba8798>:0

=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

Received signal SIGSEGV
Stack trace:
0x00007ffc4be14f6f (webrtc) ContextCreatePeerConnectionWithConfig
0x000002444a1ec07b (Mono JIT Code) (wrapper managed-to-native) Unity.WebRTC.NativeMethods:ContextCreatePeerConnectionWithConfig (intptr,string)
0x000002444a1ebfbb (Mono JIT Code) [Context.cs:82] Unity.WebRTC.Context:CreatePeerConnection (string) 
0x000002444a1ebe63 (Mono JIT Code) [RTCPeerConnection.cs:437] Unity.WebRTC.RTCPeerConnection:.ctor (Unity.WebRTC.RTCConfiguration&) 
0x000002444a1eb5d3 (Mono JIT Code) [WebRtcReceiver.cs:101] WebRtcReceiver:SetUpPeerConnection () 
0x000002444a1ea97b (Mono JIT Code) [WebRtcReceiver.cs:41] WebRtcReceiver:Start () 
0x00000244a6f441c0 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
0x00007ffc4b68e460 (mono-2.0-bdwgc) [mini-runtime.c:2812] mono_jit_runtime_invoke 
0x00007ffc4b612902 (mono-2.0-bdwgc) [object.c:2921] do_runtime_invoke 
0x00007ffc4b61b95f (mono-2.0-bdwgc) [object.c:2968] mono_runtime_invoke 
0x00007ff64d7a15b4 (Unity) scripting_method_invoke
0x00007ff64d799f55 (Unity) ScriptingInvocation::Invoke
0x00007ff64d7639ed (Unity) MonoBehaviour::InvokeMethodOrCoroutineChecked
0x00007ff64d763b18 (Unity) MonoBehaviour::InvokeMethodOrCoroutineChecked
0x00007ff64d75e982 (Unity) MonoBehaviour::DelayedStartCall
0x00007ff64cc48084 (Unity) DelayedCallManager::Update
0x00007ff64d0ab126 (Unity) `InitPlayerLoopCallbacks'::`2'::EarlyUpdateScriptRunDelayedStartupFrameRegistrator::Forward
0x00007ff64d08d0cc (Unity) ExecutePlayerLoop
0x00007ff64d08d1a3 (Unity) ExecutePlayerLoop
0x00007ff64d093fe9 (Unity) PlayerLoop
0x00007ff64e4a1e61 (Unity) PlayerLoopController::UpdateScene
0x00007ff64e48773f (Unity) PlayerLoopController::EnterPlayMode
0x00007ff64e49cffd (Unity) PlayerLoopController::SetIsPlaying
0x00007ff64e49fd64 (Unity) Application::TickTimer
0x00007ff64ee04661 (Unity) MainMessageLoop
0x00007ff64ee086f1 (Unity) WinMain
0x00007ff650c6e3c6 (Unity) __scrt_common_main_seh
0x00007ffcbf2d7034 (KERNEL32) BaseThreadInitThunk
0x00007ffcc061d0d1 (ntdll) RtlUserThreadStart
</code></pre>
</details>
</p>

**Comment by karasusan** [comment] 2021-02-19 01:19
I will try to reproduce soon.
This is a critical issue if it is reproduced, we will make the hot-fix version ASAP.

**Comment by karasusan** [comment] 2021-02-19 07:21
I checked this unit-test code but not reproduced the crash yet. 😞 

- Windows 10
- Unity Editor 2020.2.3f1
- com.unity.webrtc 2.3.2
- Quadro RTX 5000

<details><summary>TEST CODE</summary>
<p>

```csharp
using NUnit.Framework;
using Unity.WebRTC;

public class NewTestScript
{
    [SetUp]
    public void SetUp()
    {
        WebRTC.Initialize(EncoderType.Software);
    }

    [TearDown]
    public void TearDown()
    {
        WebRTC.Dispose();
    }


    // A Test behaves as an ordinary method
    [Test]
    public void Test()
    {

        RTCConfiguration GetSelectedSdpSemantics()
        {
            RTCConfiguration config = default;
            config.iceServers = new[] { new RTCIceServer { urls = new[] { "stun:stun.l.google.com:19302" } } };
            return config;
        }

        var configuration = GetSelectedSdpSemantics();
        var peer = new RTCPeerConnection(ref configuration);
    }
}
```
</p>
</details>

**Comment by Felix-N** [comment] 2021-02-19 13:06
not sure if it is related, but running the samples on my pc results in crashes too.

**Comment by karasusan** [comment] 2021-02-19 14:21
@Felix-N 
Could you have a crash log?

**Comment by mt3312** [comment] 2021-02-22 19:45
Hey, I'm having the same issue as @Felix-N

**Comment by Felix-N** [comment] 2021-02-23 15:19
@karasusan 

Are these the logs you're looking for?
[Editor.log](https://github.com/Unity-Technologies/com.unity.webrtc/files/6029809/Editor.log)
[error.log](https://github.com/Unity-Technologies/com.unity.webrtc/files/6029810/error.log)

**Comment by karasusan** [comment] 2021-02-24 01:17
@Felix-N 
Thanks.

I have not ever tried to use it in combination with the `MixedReality-WebRTC` package.
I want to know the issue caused by the combination or not.

**Comment by karasusan** [comment] 2021-02-24 01:20
@Angelo-Gebauer
@mt3312

Can I check a crash log? thanks.

**Comment by Felix-N** [comment] 2021-02-24 09:39
@karasusan 
I'm currently quite new to unity and testing if it would be a solution for us.

I've in the same project both MixedRealityWebRTC and Unity.WebRTC - though only one per scene.
It is just a test project.

A bit off topic, but perhaps you could shed some light (i couldn't test it with unity.webrtc yet):
- We want to connect to multiple peers (up to 5 for now). An instantiation of a single webrtc session per peer would work.
- Each peer should receive its own camera (and sends) - meaning we have multiple hardware cameras and need to select the right camera for each webrtc session
- In addition we'd like to optionally share screen(s) (without turning the camera video off).
- Is perfect negotiation supported?
- Can we use spatial audio rendering with webrtc in unity?

**Comment by karasusan** [comment] 2021-02-24 10:06
@Felix-N 

> Is perfect negotiation supported?
No, not yet. WebRTC package is not providing a signaling implementation.
Unity Render Streaming package provides the signaling feature, but this is not implemented the perfect negotiation.

> Can we use spatial audio rendering with webrtc in unity?
No, audio rendering in Unity is not supported yet.

**Comment by Felix-N** [comment] 2021-02-24 10:36
@katsumasa thanks.
on perfect negotiation i may have been unclear. I understand that signaling will not be part of the webrtc package.
I believe it comes down to the event onnegotiationneeded and the version of the webrtc library, meaning rollback to SRD

**Comment by karasusan** [comment] 2021-02-25 01:05
@Felix-N 
This page describes "perfect negotiation" which I mean.
https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Perfect_negotiation

We are making WebRTC APIs for supporting the perfect negotiation, but it is incomplete yet.
For example `RTCPeerConnection.RestartIce()` method is not supported right now.

**Comment by Felix-N** [comment] 2021-02-25 10:58
@karasusan absolutely right. thanks, any timeframe on this?

**Comment by karasusan** [comment] 2021-02-26 02:06
We will make a sample scene to representing the perfect-negotiation sample again.
I think it is in April.
https://webrtc.github.io/samples/src/content/peerconnection/perfect-negotiation/

**Comment by Angelo-Gebauer** [comment] 2021-03-01 08:39
@karasusan Could we please focus on the actual issue of this topic?
The crash log is in my first posting. Do you need more of it? The rest is just generic loeding etc.

**Comment by karasusan** [comment] 2021-03-01 08:55
@Angelo-Gebauer 
Hi, we could not reproduce this crash using your code in my environment.
Do you have a Unity project to reproduce it?

**Comment by Angelo-Gebauer** [comment] 2021-03-01 09:13
Can i send it to you in private somehow? Also, please be aware that (like i described above) the project crashes on 2 of our 3 machines. So if it doesn't crash on yours, doesn't mean there's no issue.

**Comment by karasusan** [comment] 2021-03-02 01:37
@Angelo-Gebauer
I see.
You can post the DM on the Unity forum.
https://forum.unity.com/members/kazuki_unity729.1918555/

**Comment by karasusan** [comment] 2021-08-19 02:37
@Angelo-Gebauer 
Hi, I would like to close this ticket. 
Are you ok with it?

**Closed** 2022-02-02 02:41 UTC
Labels: bug, stabled
