### ISSUE TITLE
streaming to and from unity synchroniously

### ISSUE THREAD

**Issue by subjectdenied** [Unity-Technologies/com.unity.webrtc#249] opened 2020-11-08 21:30 UTC
this is less a bug, then a question, i guess: in the documentation i found this:

"It is not possible to send and receive video in a single VideoStreamTrack instance"

does this mean i cannot up- & downstream a video using the same renderstreaming instance? cause the behaviour i see is that, i can either receive a video in unity or stream a video to a browser. trying to to this at the same time (to for an example use the source for manipulating the frames and return them again), results in an error regarding "localdescription sdp not kStable" (which seems to result from the plugin). i also tried to change the renderstreaming.cs so it offers first instead of taking the offer, with the same result - it always errors on setting the description in unity

using the sendvideo.js from within 2 browsers for an example seems to do exactly this, it shows both videos in both browsers

**Comment by karasusan** [comment] 2020-11-09 01:13
> does this mean i cannot up- & downstream a video using the same renderstreaming instance?

No, you can use the same renderstreaming instance for bidirectional video streams.
We are making the sample to show the use-case like you want. This will be released soon.
https://github.com/Unity-Technologies/UnityRenderStreaming/pull/338

**Comment by subjectdenied** [comment] 2020-11-12 12:33
i found the following now:
maybe i didn't understand this correctly (refering to "decoding is software only for now"), but having "hardware encoding" enabled in the RenderStreaming component, while doing bidrectional streaming, the unity side can't create the local description:

Failed to set local answer sdp: Failed to set local video description recv parameters for m-section with mid='0'.

this happens on both linux and windows, it works on windows if the toggle for hardware support is disabled, it then works on linux too, however i get a black stream back to browser in linux (this might be an issue in my code however, caused by code inconsistences when copying from/to my linux or windows machine for testing). also using opengl in linux when doing this (bidirectional steraming with hardware encoding disabled) crashes for me, using vulkan is working

this behaviour (local description error on enabled hardware encoder) is very easy to reproduce:
- have a script (for an example the video-send.js) that does bidirectional streaming at the webserver
- add a videoreceiver + camerastreamer on unity
- make sure commented code for addtransceiver in RenderStreaming.cs and VideoReceive.cs is enabled
- stream the received video to a canvas rawimage
- capture the whole cam with the camera-streamer

i'm not sure, but i debugged what arrives in unity from the browser, and it seems while setting the local description errors, the real issue is from the received stream (decoding) not working with hw-encoding enabled. also is there a order in how the receiver or capture has to be enabled?

i prepared a very simple example showing this behaviour, plz let me know, if you need it

**Comment by karasusan** [comment] 2020-11-24 00:09
OK, I will try to reproduce it.

**Comment by subjectdenied** [comment] 2020-11-24 00:11
thanks!

**Comment by karasusan** [comment] 2020-11-24 06:53
I'd like to ask you a question to solve the issue.
Are you trying to use the combination of the HW encoder and the SW decoder? 
Unfortunately, the combination is not supported yet.

WebRTC checks available codecs of sender and receiver.
The following log shows the SDP error occurs when not found the available codecs.
```
Failed to set local answer sdp: Failed to set local video description recv parameters for m-section with mid='0'.
```

**Comment by subjectdenied** [comment] 2020-11-24 12:10
@karasusan yes this happens on both windows and linux with the "hardware" toggle enabled, using software only works in windows, but crashes in linux on both vulkan and opengl

**Comment by karasusan** [comment] 2020-11-25 01:59
Thanks, @subjectdenied 

I am understanding to support *hardware decoder* (for H.264 codec) using NVIDIA graphics card.
We already finished developing the HW decoder on MacOS using VideoToolbox, and we would release it for the next version.
I will investigate crashes on Linux.

**Comment by subjectdenied** [comment] 2020-11-25 17:58
probably you should change renderstreaming.cs "hardware encoder supported" toggle, so it makes sure this means to a user that decoding wont work at all, cause it only is software for now - which is disabled when the toggle is on - this is very confusing, if you dont know about how stuff works internally

also while you are at it, a hw-encoding/decoding solution on linux where no cuda is needed, would be very much appreciated

**Comment by karasusan** [comment] 2020-11-26 01:58
@subjectdenied
> probably you should change renderstreaming.cs "hardware encoder supported" toggle, so it makes sure this means to a user that decoding wont work at all, cause it only is software for now - which is disabled when the toggle is on - this is very confusing, if you dont know about how stuff works internally

It is exactly. 
We should rethink the design of the inspector.

**Comment by karasusan** [comment] 2020-12-17 11:27
@subjectdenied 
Our team discussed about the issue and we are trying to remove the `hardware encoder supported` parameter from `RenderStreaming` inspector.

Instead of the parameter, we will add the codec list which developers can sort codecs by priority. 

This image is only a mock.
![Dec-17-2020 20-15-34](https://user-images.githubusercontent.com/1132081/102481252-d22e5c80-40a4-11eb-9c5c-e2f4d26935e6.gif)

**Comment by pilzinho** [comment] 2021-07-14 13:46
> @subjectdenied
> I'd like to ask you a question to solve the issue.
> Are you trying to use the combination of the HW encoder and the SW decoder?
> Unfortunately, the combination is not supported yet.
> 
> WebRTC checks available codecs of sender and receiver.
> The following log shows the SDP error occurs when not found the available codecs.
> 
> ```
> Failed to set local answer sdp: Failed to set local video description recv parameters for m-section with mid='0'.
> ```

Hi!
A bit late to the party ;) I just came across this issue because I got the same SDP error when one machine wouldn't display the stream when hardware encoding was enabled. The receiver uses a browser based on QT WebEngine which is based on Chromium. So I figured that this doesn't support h264 decoding. Using software/VP8 it works. Or do I have to install something on that machine to be able to decode the h264 stream?
Anyway, it would have been very helpful if the meaning of this SDP error would have been somewhere in the documentation. So people know what to look for when the stream is not shown. Would have saved me a few hours :)

**Comment by karasusan** [comment] 2022-02-02 02:45
#272 related issue

**Comment by karasusan** [comment] 2022-06-23 02:33
We supported NvCodec H.264 decoder.
Can I close this issue?

**Closed** 2022-07-13 02:40 UTC
Labels: bug, duplicate, waiting for release, issued
