### ISSUE TITLE
The latest Google browser(Version 114.0.5735.91 (Official Build) (64-bit)), webrtc video parsing error: 

### ISSUE THREAD

**Issue by Westlife0012** [Unity-Technologies/com.unity.webrtc#918] opened 2023-05-31 03:07 UTC
### Package version

3.0.0-pre.5

### Environment

```markdown
* OS:Window 11
* Unity version:Unity 2020.2.6
```

### Steps To Reproduce

1. First,we use webrtc version 2.4.0-exp10,  It is normal in chrome 109.0.5414.120(Official Build) (64-bit)), but in Chrome Version 114.0.5735.91 (Official Build) (64-bit)  . framerate start dropped,when receiving 50 frames per second, only 10 frames can be parsed.
2. We upgrade webrtc version to 3.0.0-pre5.  In chrome 114.0.5735 version ,frame still drop .Sometimes the screen may have a blurred appearance. But in Chrome Version 109.0.5414.120,everything was right.

Have you tested it in chrome 114.0.5735 version(The latest version)?
Are the latest Google Chrome incompatible with  our webrtc packages?

Please help me,thanks!

**Comment by karasusan** [comment] 2023-06-02 02:13
@Westlife0012
Hi, I will check this issue. Can you see the video codec?

**Comment by Westlife0012** [comment] 2023-06-02 02:48
Yes,Video codec is H264 .Everything is ok while video codec is vp8.
There is no problem wheile use old version of chrome,even if codec is h264.
![1](https://github.com/Unity-Technologies/com.unity.webrtc/assets/22436832/ff8c484e-1582-4939-ab58-4bbaa5a9168b)

**Comment by Westlife0012** [comment] 2023-06-02 02:52
Same computer,same network,  latest chorme version will drop frame or blurred.  old chrome version is ok.
I am very confused...
webrtc version is  3.0.0-pre5..

**Comment by karasusan** [comment] 2023-06-05 04:27
I tested in my environment, but the issue is not reproduced.
I am using the webrtc version 3.0.0-pre.5.

![image](https://github.com/Unity-Technologies/com.unity.webrtc/assets/1132081/7e50ccc2-f0b4-49c5-9df4-4e869ddf227b)

**Comment by Westlife0012** [comment] 2023-06-05 04:50
Ok,i will test with the same demo.Maybe I need to change the connection method.

**Comment by kannan-xiao4** [comment] 2023-06-20 05:39
@Westlife0012 We close this issue. if you have any problem about this, please re-open issue. Thanks.

**Closed by kannan-xiao4** 2023-06-20 05:39 UTC
Labels: bug, stabled
