### ISSUE TITLE
[BUG] Can't use Texture2D as source for VideoStreamTrack on iOS

### ISSUE THREAD

**Issue by Kawottex** [Unity-Technologies/com.unity.webrtc#360] opened 2021-04-09 09:01 UTC
Hello,
Using a Texture2D as source for a VideoStreamTrack is working correctly in my Unity Editor on Windows. 
But when I switched on an Apple Mac to deploy it on an iPhone, the editor crashed after creating the VideoStreamTrack object. When deployed on an iPhone, I got the following error:

> -[MTLTextureDescriptorInternal validateWithDevice:]:1248: failed assertion `Texture Descriptor Validation
MTLTextureDescriptor has invalid pixelFormat (0).

Here is a simple repro:
```C#
void Start()
    {
        WebRTC.Initialize(EncoderType.Software);
        StartCoroutine(WebRTC.Update());
        Texture2D tex = new Texture2D(1, 1);
        VideoStreamTrack videoTrack = new VideoStreamTrack("TestTrack", tex);
    }
```

I got the latest released version of Unity WebRTC (M89) and macOS Catalina (Version 10.15.7).

Thank you,
Kevin

**Comment by kannan-xiao4** [comment] 2021-04-11 23:57
Hi, @Kawottex 

if we need to use struct texture format, so please try below code for creating Texture2D

```
        public static TextureFormat GetSupportedTextureFormat(GraphicsDeviceType type)
        {
            switch (type)
            {
                case UnityEngine.Rendering.GraphicsDeviceType.Direct3D11:
                case UnityEngine.Rendering.GraphicsDeviceType.Direct3D12:
                case UnityEngine.Rendering.GraphicsDeviceType.Vulkan:
                    return TextureFormat.BGRA32;
                case UnityEngine.Rendering.GraphicsDeviceType.OpenGLCore:
                case UnityEngine.Rendering.GraphicsDeviceType.OpenGLES2:
                case UnityEngine.Rendering.GraphicsDeviceType.OpenGLES3:
                    return TextureFormat.ARGB32;
                case UnityEngine.Rendering.GraphicsDeviceType.Metal:
                    return TextureFormat.BGRA32;
            }
            throw new ArgumentException("Graphics device type not supported");
        }

        var format = GetSupportedTextureFormat(SystemInfo.graphicsDeviceType);
        var tex = new Texture2D(100, 100, format, false);

```

**Comment by Kawottex** [comment] 2021-04-13 10:16
Hello, thank you for your answer, it works well on my iPhone. 
Nevertheless, it seems that my Unity Editor on Mac still crash, even with this fix.
It's not a huge problem for me because I do most of my test on Windows or iPhone, but I think it can be helpful to investigate that issue.

**Comment by karasusan** [comment] 2021-04-19 02:22
We are investigating the crash caused by the colorspace.
Thanks.

**Comment by karasusan** [comment] 2021-04-22 03:35
#370 is merged.

**Closed** 2021-04-26 01:44 UTC
Labels: bug, waiting for release
