### ISSUE TITLE
[BUG]: Camera.Capturestream does not include composite layers

### ISSUE THREAD

**Issue by BoyBouw** [Unity-Technologies/com.unity.webrtc#616] opened 2022-01-27 19:12 UTC
### Package version

2.4.0-exp.5

### Environment

```markdown
* OS:Windows
* Unity version:2021.2
```

### Steps To Reproduce

1. Include a composite layer, e.g. an OVROverlay in your scene. 
2. Capture the scene using CameraExtension.CaptureStream
3. The "captured" stream only includes the eye buffer, not the composited image including the OVROverlay

### Current Behavior

CaptureStream only captures eye buffer, not composite layers. 

### Expected Behavior

CaptureStream captures everything the end-user sees, including Overlays and Underlays.

**Comment by karasusan** [comment] 2022-02-02 02:49
@BoyBouw
Can I share your Unity project to reproduce the issue?

**Comment by julienkay** [comment] 2022-02-03 11:02
Just chiming in here with some info, because imho this is not a bug, but how compositor layers (as implemented in OVROverlay for example) work by design:

This type of rendering is done by the Oculus system software directly, when deciding how to render the eye buffer provided by the application to the screen (taking into account temporal/spatial reprojection etc.). The contents of the compositor layers are sampled directly and never end up in the eye buffer at any point, so they can't be captured by the application. In case of Oculus Passthrough this is also a security measure to avoid giving developers direct access to the video stream that the HMD sees.

- If you're content in the OVROverlay is static (e.g. an image/video that you have access to) and you want to have it included in a capture in your application, the solution would be to not use compositor layers and let Unity render the content in Unity directly.
- If the intention was to record passthrough video, that is currently not possible as far as I know.

**Comment by kannan-xiao4** [comment] 2022-02-08 02:23
@BoyBouw  we think @julienkay correct.
If not depend on OVROverlay, please share your project to  reproduce the issue.

**Comment by BoyBouw** [comment] 2022-02-08 06:31
> Just chiming in here with some info, because imho this is not a bug, but how compositor layers (as implemented in OVROverlay for example) work by design:
> 
> This type of rendering is done by the Oculus system software directly, when deciding how to render the eye buffer provided by the application to the screen (taking into account temporal/spatial reprojection etc.). The contents of the compositor layers are sampled directly and never end up in the eye buffer at any point, so they can't be captured by the application. In case of Oculus Passthrough this is also a security measure to avoid giving developers direct access to the video stream that the HMD sees.
> 
> * If your content in the OVROverlay is static (e.g. an image/video that you have access to) and you want to have it included in a capture in your application, the solution would be to not use compositor layers and render the content in Unity directly.
> * If the intention was to record passthrough video, that is currently not possible as far as I know.

To clarify, I was using the OVROverlay to play a video, which has I significant quality boost. I get your point. I think this is intended behaviour. This is not an issue with this library. If anyone else has this issue, I fixed it by using rendering the video onto a skybox. The quality is definitely not the same, but I can stream this at least.

**Comment by kannan-xiao4** [comment] 2022-02-22 03:15
@BoyBouw Thanks for sharing your know-how.
If you have no other questions, can I close this ticket ?

**Comment by BoyBouw** [comment] 2022-02-22 06:13
> @BoyBouw Thanks for sharing your know-how. If you have no other questions, can I close this ticket ?

Yes, thanks!

**Closed** 2022-02-22 09:00 UTC
Labels: bug, stabled
